# http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/
# http://askubuntu.com/questions/125342/how-can-i-install-python-2-6-on-12-04
language: python
install:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install -y python2.6 python2.6-dev
  - pip install tox
script:
  - tox
env:
  - TOXENV=py26-django15-cms2
  - TOXENV=py26-django16-cms3
  - TOXENV=py27-django15-cms2
  - TOXENV=py27-django16-cms3
